### ISSUE TITLE
Support for Avalon Player API

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#166]
# Description
Ramp should be able to be controlled with Javascript, at a first pass implementation supporting the existing Avalon API: https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953578/Player+API.

# Current player API implementation
JS Code supporting it (only 8 lines): https://github.com/avalonmediasystem/avalon/blob/d37bc1703085eef26affe53d9f23695148666179/app/views/master_files/_player.html.erb#L27-L34

# Examples
- https://iumusiclive.music.indiana.edu

# Done Looks Like
- [ ] Ramp responds to methods as specified in https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953578/Player+API

**Comment by masaball** [comment]
We are not currently using Ramp for the embedded player, instead we are currently building it from standard VideoJS. [Avalon PR 5394](https://github.com/avalonmediasystem/avalon/pull/5394) adjusts the existing JS for interacting with MediaElement so that it will trigger the proper actions in VideoJS.

Since Ramp is also a VideoJS player, when we switch to a Ramp based embedded player it should hopefully be plug and play with the updated code. We should hopefully just need to switch out the video element ID being searched for, if the Ramp generated ID is different from what is currently being assigned.

**Comment by masaball** [comment]
The main purpose of the Player API is to allow sites using the embedded player to create their own control buttons on their page rather than relying on the built in controls of the player. In order to test the functionality, you need to embed a player and provide buttons and appropriate event listeners. For my own testing, I ended up cribbing the example from [our documentation's](https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953578/Player+API) example API client section.

Then I used [JSFiddle.net](https://jsfiddle.net/) for the testing. In the html section, I entered the iframe embed from my local instance and the HTML from the documentation for the various buttons. Then in the javascript section I copied over the JS code which is the bit between the `<script>` tags in our example api client.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzhOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad8a5ede938aab25768d10b52b82789266de7f8/Screenshot_20231005_164225.png)

A few notes:
- `target_domain` in the JS code is the parent domain of the player. So, testing from Avalon-dev should be `var target_domain = "https://avalon-dev.dlib.indiana.edu"`
- You need to include JQuery in a `<head>` section in the HTML for the code to work in JSFiddle. You can copy `<head><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script></head>` to the top of the HTML section. 
- Embeds from Avalon do not include an ID field in the iframe element so you will need to add one to work with the code from our documentation. I went with `<iframe id="player_iframe" src=...></iframe>` because "player_iframe" is the ID used in the example code. It is arbitrary, but if you use something else you will also need to change `var f = $('#player_iframe');` in the JS code to match e.x. `id='example'` would require `var f = $('#example');` 

Once everything is situated with the code, hit "Run" in the upper left corner and the bottom right panel should load the player with a series of buttons next to/below it. There isn't any CSS, so the formatting isn't pretty. But all of the external buttons should trigger the proper behaviors from the player. 

One more note, the toggle loop functionality may not work properly in every browser because it uses the `autoplay` html attribute and not every browser, especially mobile browsers, respects that. If the loop is not autoplaying you can pull up your browser's html inspector and see if pushing the button is adding/removing the `loop` and `autoplay` attributes in the video player element.

@elynema

**Comment by elynema** [comment]
@masaball Thanks so much for the detailed explanation. I noted one thing - the very first time I run it, the buttons don't work. If I run it again, the buttons do work appropriately. Did you have that experience?

**Comment by masaball** [comment]
I did not experience that so I'm unsure what might be going on. Since it works the second time, it may have been a loading issue within JSFiddle potentially?

**Comment by elynema** [comment]
I am going to go ahead and close this at this point as completed.
