### ISSUE TITLE
[BUG] Caption options displaying twice

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#295]
# Description

When a file (canvas) is selected in Ramp that has a single .vtt being provided as a caption (in Avalon), the file is listed twice when clicking on the closed caption button in Ramp. This is duplicative.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88c057b7f9cceb755a01900d0df20aeda796e6cc/image.png)

Here is another example: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p

# Done Looks Like
- [x] Each caption file that is available in Avalon should be listed once in the CC dialogue in Ramp, even if it is present in both the manifest and the HLS stream.

**Comment by joncameron** [comment]
Caused by the captions being in the hls manifest as well as the IIIF manifest. This may require handling to ensure that only one file being accepted.

**Comment by Dananji** [comment]
From what I understand, VideoJS is adding any tracks we provide via the `tracks` option to its list which includes the subtitle/caption tracks from the HLS manifest. Since we have the subtitles/captions tracks in the HLS manifest repeated in the IIIF Manifest, we are seeing the duplication.

When we override this behavior, it doesn't add the caption settings options to the captions menu. I will have to go through the code and see why this is happening.
And further investigate, if there's a way for us force VideoJS to add the captions settings options without the duplication.

I don't see any accessibility guidelines for the caption settings (for font-size, color, etc.), but there's a guideline for resizing text: https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1#resize-text
But I don't see anything specific for adjusting font-sizes for captions.

**Comment by Dananji** [comment]
Related code in VideoJS (https://github.com/videojs/video.js/blob/d535e163da3f1df5d87f7f7a1a2e8ff628361afb/src/js/control-bar/text-track-controls/subs-caps-button.js#L66-L67):
```
if (!(this.player().tech_ && this.player().tech_.featuresNativeTextTracks) &&
      this.player().getChild('textTrackSettings')) {
      items.push(new CaptionSettingsMenuItem(this.player_, {kind: this.label_}));

      this.hideThreshold_ += 1;
    }
```
Here `featuresNativeTextTracks` is assigned the value of `nativeTextTracks`.
To turn on captions setting we need `textTrackSettings: true`, and to avoid captions/subtitles option duplication we need: `html5: { nativeTextTracks: true }`, which doesn't work in our use-case.

**Comment by elynema** [comment]
Test this in Safari and on iOS device to determine if we are still able to see captions in these environments.

**Comment by joncameron** [comment]
This also needs to be tested in Safari; native player on iOS required caption file info within the HLS manifest.

**Comment by elynema** [comment]
This seems to be working correctly in Safari; not testing yet on a mobile device.

@joncameron Do we want captions to be turned on by default? Right now, they seem to be off by default.
