### ISSUE TITLE
Transcript Download Doubles Extension

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#309]
# Description
Downloading a Word document or text file from the Transcript component is adding an extra extension to the end of the existing full filename. 

# To Reproduce
- ramp.avalonmediasystem.org
- Use https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d/manifest.json
- Select the 2nd section
- Go to the Transcript tab and download 
- "The Legislative Organization of Congress.doc" downloads as "The Legislative Organization of Congress.doc.doc"

The original filename for supplemental files is still present in ActiveStorage in Avalon, so this could be gone back and get retrieved.

# Done Looks Like
- [ ] Storage added to retain the original filename for transcript files (or confirmed that this is the case)
- [ ] File names when downloaded are the original specified filename (except when "machine-generated" info text is inserted to the filename before the extension(s)

**Comment by joncameron** [comment]
Special handling for file downloads for different formats are causing this behavior.

**Comment by elynema** [comment]
Because users can edit the file name in Avalon, it might not contain an appropriate extension. So Ramp attempts to detect the extension and provide it for easier file opening when downloaded.

While Avalon could provide both the file label and original file name to Ramp, it would likely be disconcerting for users to see the user-specified label in the transcript drop-down box and then a completely different filename on download.

@masaball Does it make more sense to solve this problem in Avalon and have Avalon create the file label + extension in the manifest so that Ramp doesn't have to do any special work?

**Comment by masaball** [comment]
No, this particular issue would not be solved by changing anything in Avalon. Checking the manifest again all of the needed info is present in the manifest, including the file name having having an extension. There are just edge cases in Ramp's processing that are being hit. In this case it is a file that has been labeled as ".doc" but the mime type is "text/html" rather than "application/msword". This discrepancy is what caused the improper handling.

There may be a worthwhile discussion to be had about how filenames are generated in Avalon and what processing Ramp should be responsible for, but that feels like a larger discussion than encompassed by this ticket.

**Comment by elynema** [comment]
@masaball There is some weirdness happening for a transcript download with a particularly unusual filename on this record: 

https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p

See the transcript for section #2 - lunchroom_manners.mp4. Improbably, the transcript file is transcript-stuck-and-jumps-in-page-780p.mov. When I attempt to download it using the download transcript button, it calls it transcript-stuck-and-jumps-in-page-780p.mov.doc. This obviously does not make my computer happy.

Perhaps there is something that is defaulting to .doc for unusual file extensions? If I remove the .doc file extension, it is a video (.mov) that plays properly in quicktime.

**Comment by masaball** [comment]
The changes I made to the Ramp file download function were to strip anything that looked like an extension from the filename and then rely on the browser to insert the proper extension upon downloading. The exception to this were files uploaded as transcripts that are in an unsupported format, with the example I was testing with being a `.html` file. For these files, the original behavior in Ramp was to replace the extension with `.doc`. I chose to keep that behavior in place because I assumed there was a rationale behind it and changing it would have been out of scope of this ticket.

Additionally, when initially working on this ticket I only looked at the "Transcript Download" button found in the Transcript component. I did not think to test out downloading files from the "Files" tab or from the file download button that renders in the player since this ticket was scoped to just the Transcript component (I believe we have the option for the video player based download button disabled in Avalon but it would be good to verify consistent behavior with all download options).

In QA, @elynema found a file that was still receiving multiple extensions (`.mov.doc` from the download transcript button). I did follow up testing and was able to confirm that we are seeing different behavior between browsers and between the transcript component and "Files" tab.

Firefox:
- Transcript component: .qt
- Files tab: .mov.doc

Chrome:
- Transcript component: .doc
- Files tab: .mov.doc

Because Avalon allows the upload of any file type as transcript, it does not seem sufficient to assign unsupported file formats a `.doc` extension. At best, this produces a file full of gibberish, at worst the computer thinks the file is corrupted and won't do anything with it.

Do we attempt to remove the file extensions and let the browsers determine for themselves what they think the appropriate file type is in all cases? Should we assign extensions within Ramp based solely on the file metadata to ensure consistency between browsers? With our current setup we have to do processing of the filename within Ramp in order to handle adding "(machine generated)" labels.

**Comment by joncameron** [comment]
My preference would be to completely avoid any file extension rewriting. File should download with the name and extension they were uploaded with, with the only processing being adding "(machine generated)" text as needed, which shouldn't involve the extension(s).

**Comment by joncameron** [comment]
We don't currently retain the original filename for supplemental files (just the label field, which is editable). And if an editor changes the filename...

We'll need to add storage to Avalon to retain the original filename for the transcript file.

**Comment by joncameron** [comment]
This will involve work on both Avalon and Ramp.

**Comment by joncameron** [comment]
Another thing I found while testing was a filename/double period extension issue: a file with the name `Harter_Abbie.vtt`renders in the Ramp Transcript component but a file named `Harter_Abbie.aviary.vtt` does not and shows the unrecognized format error. 

@masaball do you think that behavior would that change with the filename handling changes in this ticket, or should I create a new issue for it?

**Comment by masaball** [comment]
I'm not sure if the changes discussed here would fix that bug. Let's go ahead and open a new ticket so it doesn't get lost in the shuffle and we remember to test for it after these changes. Then we close it or do additional work on it as necessary.

**Comment by elynema** [comment]
Proposed solution: employ 2 labels for supplemental files in the IIIF manifest - the original uploaded filename and any label assigned to it in the Avalon interface. The human-generated label will have a language encoded; the original uploaded filename will not have a language encoded.

**Comment by masaball** [comment]
Note for QA:

There are some download cases where the browser will provide the extension instead of Ramp's processing. This can result in seemingly inconsistent behavior. In my testing during development, I saw one case in particular where the file was a Quicktime Format File and I got:
- `.mov` on Windows systems
- `.qt` on MacOS
- No extension on Linux

While this seems inconsistent, `.qt` and `.mov` are interchangeable and Linux does not require file extensions so the file was fully functional on all systems I tried it on, both desktop and mobile. I think as long as any downloaded files do not have multiple extensions and none of the files seem to be corrupted due to incorrect extensions we are good to go.

**Comment by joncameron** [comment]
I created a test object for this which includes multiple file types: https://avalon-dev.dlib.indiana.edu/media_objects/rn301139z.

All of the files downloaded with the expected filename (original filename, not the label name). Tested with txt, doc, docx, pdf, vtt, and with the machine generated option.
