### ISSUE TITLE
[BUG] placeholderCanvas not displaying for inaccessible items in playlists on iOS devices

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#347]
# Description

When viewing inaccessible (or lock icon) items in a playlist on an iOS device in either Safari or Chrome, the black rectangle with placeholderCanvas text does not appear. Instead, the player simply disappears and only the playlist item title shows with markers / source item details below.

This happens on the Ramp demo site, as well, so suspect it is a Ramp issue.

Tested on iPhone 11 in Browserstack.

I have not tested inaccessible / items on the media player page to see if the same thing happens there.

<img width="412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f453659e65bc06972bde03a13622e50d81503b08/bs_realios_Mobile_iPhone%2011-13.0.jpg" alt="bs_realios_Mobile_iPhone 11-13.0.jpg" />

**Comment by Dananji** [comment]
This can be tested on Ramp demo site.

**Comment by joncameron** [comment]
Testing on the Ramp site with https://avalon-dev.dlib.indiana.edu/playlists/94/manifest.json, I see the empty player but not the "You do not have permission to playback this item." message for an inaccessible item. Looks like that div with the text is present on the page but not displaying inside the blank player area. 

@Dananji is this something that could be fixed with a styling change?

**Comment by Dananji** [comment]
The new styling changes worked in the PR were not reflected in the demo site, since the CSS files were not re-built on the Netlify deploy.
I built the CSS files manually and pushed them to `main`, so the demo site now uses the new CSS changes in the PR.
