### ISSUE TITLE
[BUG] Volume controls not working in media player on Android devices

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#352]
# Description

Volume cannot be adjusted in non-full screen or full-screen player mode on Android devices. It just toggles back and forth between muted and un-muted when you click on it to try to open the slider. This is only on video; audio volume can be adjusted because it is a static control. Use user agent or other signifying value to change configuration in Video.js for iOS and Android devices

Tested with Samsung Galaxy on both Chrome and Firefox.

We'll check what exists in the Avalon 7.6 code for handling these cases and implement in 7.7 as appropriate. 

# Done Looks Like
- [x] Volume slider is disabled/does not appear in the media player for video content in iOS and Android (phone and tablet) devices/browsers
- [x] Volume button functions as a mute/unmute button (no volume slider) for video in iOS and Android (phone and tablet) devices/browsers
- [x] Change user agent or other signifying value check in Video.js configuration to suppress volume slider

**Comment by joncameron** [comment]
In Mediaelement.js, we didn't include the volume slider. For mobile devices in the current case, we could omit that as well in the UI. For iPad, need to include touch handlers in js to accommodate this case.

**Comment by masaball** [comment]
Implementing just touch handlers for iPad/tablet is not sufficient for changing the behavior here. The Volume icon itself in VideoJS is part of the mute toggle button. There is no way provided in the VideoJS options to turn off just the mute toggle functionality. 

Options for changing this behavior in iPad/tablet that I can see (from easiest to hardest, more or less):
1. Completely disable the volume panel like we are implementing for other mobile devices.
2. Disable only the volume slider, so that the button is just a mute toggle, relying on the user to use device controls for other volume changes.
3. Hack together something to prevent the mute toggle from firing and have a touch of that element open the volume slider.
4. Create a custom VideoJS component to override the mute toggle with in an iPad/tablet context.

I lean towards options 1 or 2, I think. Maybe pursue one of the other options for next release? @elynema @joncameron Any thoughts? Any other approaches anyone can think of?

**Comment by elynema** [comment]
For documentation purposes, In MCO with mediaelement.js, the volume icon is showing up in Safari and the slider is usable, but doesn’t actually change volume. Clicking the volume icon can be used for mute/un-mute. The volume icon does not show up at all in Chrome on iPad.

@masaball @joncameron  I support #2, turning it into a toggle on iPad/tablet only. Do you have an estimate for difficulty on that? I could also support #1, just removing it completely.

**Comment by Dananji** [comment]
Looking at the previous implementation of avalon player with ME.js. The [code](https://github.iu.edu/AvalonIU/Avalon/blob/main/vendor/assets/javascripts/mediaelement/mediaelement-and-player.js#L3179) indicates that it is not supposed to be building the volume control entirely if it is Android or iOS. So volume controls not showing up in Chrome is expected, but I don't know why it is showing up in Safari in iPads.

**Comment by masaball** [comment]
Implementing #2 is a 2 in difficulty I think. I expect the initial code change is pretty trivial, but will require testing on browserstack for a bunch of devices and tweaking the conditionals to work for all devices may drive the time up. @joncameron Are you saying to include the mute toggle on all mobile devices? Or are we removing the icon entirely for phones and having a toggle for tablets? Just want to clarify the done looks like.

**Comment by elynema** [comment]
@masaball I am pretty sure that Jon is saying to re-enable the volume button on all mobile devices (including iPad) and just turn it into a mute/un-mute toggle. Is that still a 2 in difficulty?

**Comment by masaball** [comment]
Yes, it would still be a 2.

**Comment by joncameron** [comment]
@masaball Should I create a new ticket scoped to this for 2 points, or do you feel like that would fall within what we've pointed for this issue?

**Comment by masaball** [comment]
I think it falls within what we have pointed for this issue. If you could change the done looks like on this ticket to match the change in requirements, I think we are good.

**Comment by joncameron** [comment]
@masaball Done looks like is updated.

**Comment by elynema** [comment]
Tested on Ramp demo site and looks good on iPad and Android (not relevant in iOS since it uses the native player). Slider is still there in Safari and Chrome on laptop.

**Comment by joncameron** [comment]
I tested in Avalon and looks good to me too.
