### ISSUE TITLE
Captions Do Not Appear in iOS Fullscreen Player

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#382]
# Description
Captions are displaying as expected in the media player's standard view in iOS, but entering fullscreen puts the media in the native player context, which is not receiving the captions and does not render any even when available.

# Reproduce
In iOS, go to https://ramp.avalonmediasystem.org/ or https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d and enter full screen playback.

# Done Looks Like
- [ ] When available, captions appear in the native media player in fullscreen mode

**Comment by Dananji** [comment]
@joncameron I tested this in Browserstack iPhone 13 in Chrome and Safari. And in a physical device in the same browsers. I can't reproduce this. Are there particular steps to reproduce?
What I did was to open the item in avalon-dev in the browser and hit play without changing anything.

**Comment by joncameron** [comment]
@Dananji The avalon-dev item is working now and I couldn't reproduce anymore either, but the default lunchroom manners manifest on the Ramp demo site still isn't working properly. To reproduce I used Browserstack iPhone 13 with Safari and got this behavior, where entering full screen removes the captions:
<img width="402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzQ1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89f216b5595da10ea982bb71fc4114a8fc5836a7/Feb-07-2024%2011-03-39.gif" alt="Feb-07-2024 11-03-39.gif" />

**Comment by elynema** [comment]
When playing the default manifest on the Ramp demo site on iPhone iOS 17 Safari, there is a caption option that shows up in both Ramp and in the native player. However, when I turn it on in the native player, no captions actually show up. I don't know if that is an issue with that particular manifest?

The IIIF cookbook recipe works to display the captions option in the native player with the ability to turn them on/off: https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json

@Dananji @joncameron In this avalon-dev manifest, the first section has 2 captions: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p. Only the first caption option is showing in the native iOS player. We do have another issue for only the first caption showing, so I'm not sure if this issue was expected to resolve that (done looks like implies that all captions show in the native player). https://github.com/samvera-labs/ramp/issues/405

However, in this playlist example (https://avalon-dev.dlib.indiana.edu/playlists/97) the native player is showing the single caption file twice for playlist item #13 (legislative organization of congress).

**Comment by elynema** [comment]
@Dananji Confirming that I tested in Safari in another iPhone in Browserstack with cache disabled in the web inspector.

Playlists and media item contexts are behaving differently, even when it's the same item with the same set of captions. I added 2 captions to a record that had none to try to make sure there weren't historical record oddities interfering.

1. On the media item page in Ramp demo site: https://avalon-dev.dlib.indiana.edu/media_objects/000000000/manifest.json. As found above, both the captions show in Ramp, but only the first caption shows up as an option in the native player.
2. On the playlist page in the Ramp demo site (see #9/10): https://avalon-dev.dlib.indiana.edu/playlists/94/manifest.json. In this context, the set of captions in the Ramp player are duplicated (each option appears twice in the list). Checking this against Safari on macOS, it looks like there is JS that deletes the duplicates from this list that isn't firing in the iPhone context. When these playlist items are played in the native player, both caption options show up, and the first one is duplicated in the list.

**Comment by Dananji** [comment]
I'm seeing the same behavior for these 2 examples.

In iPhones we use the native text track handling in Video.js. I don't know why it's behaving 2 different ways with media object manifest and a playlist manifest. We do not change the captions behavior for playlist manifests in Ramp. I'll take a look at the code and see what I can do.

**Comment by elynema** [comment]
Re-confirmed today that the captions recipe on IIIF site is working in Ramp.

For the issue that Dananji fixed, tested https://avalon-dev.dlib.indiana.edu/playlists/97 in iPhone and iPad Safari.

- For #31 and #32 on the playlist, the item has 2 captions. Each option displays in the Ramp player; only the first option displays in the native player. Duplication has been removed. So that seems resolved.
- In the playlist context where there is only a single caption (see #13, for example), that single option is showing properly in Ramp and the native player. So that is working as well.
