### ISSUE TITLE
[BUG] Record is showing closed caption option that doesn't exist

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#407]
# Description

Record is showing an 'english' option under CC menu in Ramp that does not appear as an actual transcript for the item. There also appears to be an empty row beneath the last caption option in the CC menu.

https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t

In Chrome:

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1a87397b1c1234879a10d2ac1cf7d7c06401331/image.png" alt="image.png" />

<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fb0052206113e73e3693aac476df923718cd7b7/image.png" alt="image.png" />

In Safari, I'm seeing a different caption label, which also doesn't exist (I did do a hard refresh!):

<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXBQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3958a0feabfb9bde54c1c973d20dcd9c61394c35/image.png" alt="image.png" />

# Done Looks Like
- [ ] The list of captions in the captions control menu only reflects the listing shown to the user under the section in the Manage Files page (extraneous list items, like "english" or a filename for a file not attached as a caption, should not appear)

**Comment by joncameron** [comment]
Probably an item with a legacy caption file that is showing up as a zombie caption; side effect of uploading multiple captions and missing surfacing/cleaning up the original.

**Comment by joncameron** [comment]
Manage Files page should also display all pre-existing caption files; may not be available right now for older captions.

**Comment by joncameron** [comment]
We'll leave this as investigation for the section files being interpreted on captions (Safari shouldn't do things like showing filename instead of "english"). After this investigation we can create a new ticket if needed for migration of legacy caption files.

**Comment by masaball** [comment]
I have checked and the item here does have legacy captions, and their filename is "lunchroom_manners.mp4.vtt". As such, I do not think that there is any accidental cross-loading of sections files.

I think the reason for the difference in display name is from the rework done for file downloading. We now pass through the label and original filename information in the IIIF manifest. I think that when we are creating the info to feed into the VideoJS tracks, it is grabbing the original filename instead of the label. So we would probably need to adjust the [getResourceInfo](https://github.com/samvera-labs/ramp/blob/ce98e1f2ba201882d50ae1c8701a2c71073d147e/src/services/utility-helpers.js#L379) function in Ramp to ignore the 'none' entry if there are multiple labels. Unsure why Safari is prioritizing the field differently than other browsers, but that is what it looks like is happening.

@joncameron Do you want to create an issue to look into that further and ensure that the user defined label is what is displayed for captions? Can probably wait until after 7.7 since there is still a label showing.

**Comment by masaball** [comment]
Closing with follow up tickets: Avalon [#5657](https://github.com/avalonmediasystem/avalon/issues/5657) and Ramp #413.
