### ISSUE TITLE
Ramp Freezes Page for Many-Sectioned Items

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#470]
# Description
A 425 section item in Media Collections Online loads in Ramp, but the page begins to behave very slowly until the page freezes completely and becomes unresponsive when navigating through the sections and playing back the media.

I tested in Safari and Chrome on macOS 14.4 and in both cases the page would eventually lock up completely.

I noticed two particular error messages when testing this record:
Uncaught promise exception in the console:
![Screenshot 2024-04-03 at 3 19 24 PM](https://github.com/samvera-labs/ramp/assets/1406618/5dcdea8c-8412-41f5-b476-bcf68c725be4)
"Stream was not recognized" flash message
![Screenshot 2024-04-03 at 3 11 57 PM](https://github.com/samvera-labs/ramp/assets/1406618/1c06d523-fc36-4e98-92d0-1a275ddc6ddb)

A public item with more sections than this one is working as expected: https://media.dlib.indiana.edu/media_objects/th83mm25s. Is there something about the example record here in particular causing these errors?

Another issue is manifests sometimes timing out and not being returned; when accessing this item sometimes a 500 is returned.

# Example Item
- https://media.dlib.indiana.edu/media_objects/5712mz82d
- https://mco-staging.dlib.indiana.edu/media_objects/5712mz82d (staging)
 
# Done Looks Like
- [ ] Further investigation into this issue and exploration of potential causes

**Comment by cjcolvar** [comment]
I did some testing and found some issues that may or may not be related:

When switching sections auto.m3u8 takes ~1.5 s, /stream takes 7s->3.3min
Ran into problem with session overflow probably given the number of sections got tokens all at the same time for this item and 600+ section item
SessionOverflow led to 500 when trying to fetch the manifest.json
Sections closed with button reexpand on rerender
There isn't a way to close a section since clicking on section header jumps to the section instead of collapsing like an accordion
Structure flashes back to beginning when switching sections
Segment changes causes focus on newly playing section which can be disorienting when scrolling through long structure

**Comment by joncameron** [comment]
Here is the large public example item for profiler testing that I shared: https://media.dlib.indiana.edu/media_objects/xg94jb936.

**Comment by elynema** [comment]
The error shown here seems to be an issue communicating with the streaming server. This is the item that Chris assembled manually for Music and may need his assistance with troubleshooting.
