### ISSUE TITLE
[BUG] Turning off captions for specific file does not remove green underline under CC widget

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#588]
**Describe the bug**
Turning off captions does not remove the green underline under the CC widget for a specific file.

**To Reproduce**
1. Go to https://avalon-staging.dlib.indiana.edu/media_objects/9c67wm82b
2. Select the third item
3. Turn captions off
4. The green underline under the CC widget icon remains

Note that this behavior was not reproducible generally across other items. It may be related to the fact that this file has a caption with a blank label?

**Expected behavior**
When captions are turned off, the green underline should disappear.

**Screenshots**
![image](https://github.com/user-attachments/assets/2adf20db-0d30-4a12-8351-8123dc9e96c6)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elynema** [comment]
I added a label to this caption, which now displays in Ramp (instead of displaying 'auto'), but it didn't change the behavior.

**Comment by elynema** [comment]
First step is to investigate what is happening with this caption to determine if there is anything we need to guard against in Ramp.

**Comment by Dananji** [comment]
The underlying issue was not related to the caption label. I was able to reproduce this bug on `avalon-dev` with the following steps;
1. Load the 5th section with the section URL: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/section/s1784k75z, which doesn't have captions
2. Select section 1 which has captions
3. Observe the green underline for the captions button is present with a default caption selected
4. Turn off captions
5. Observe the caption button's green underline is still present

The reason for this was; in the Ramp code, the reference to captions button in the function that adds/removes the green underline was broken when captions button was not setup on page load.

**Comment by joncameron** [comment]
👍
