### ISSUE TITLE
[BUG] media player is not re-sizing to width of browser

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#676]
# Description

For both audio and video items, the media player is not re-sizing to the width of the browser on the playlist page. This requires the user to scroll the browser horizontally in order to access all the widgets. So far, this has been observed in Safari on iPhone as well as Chrome on desktop (when the browser is resized down). This is happening even when the browser is not zoomed at all and is happening for both audio and video on both playlist and media item pages.

![screenshot-iPhone 15 Pro-17 0 (3)](https://github.com/user-attachments/assets/b610abef-e923-4cfc-91b2-0e9ac2114504)

# Done Looks Like
- [ ] Media player resizes to fit the entire width, including components, to within the browser viewport width
- [ ] Test zoom levels and investigate resizing strategy to determine where to make changes
- [ ] There is enough space to accommodate the popup menu for the playback speed widget.

**Comment by Dananji** [comment]
I was not able to reproduce this issue for Chrome on both my machine and BrowserStack for desktop.

**Comment by elynema** [comment]
Tested this morning and I also was not able to reproduce this specific issue in Chrome or Safari today. However, I am seeing an overlap issue in what is probably tablet mode in both Chrome and Safari. 

![image (10)](https://github.com/user-attachments/assets/c3d081ed-6770-47e1-829e-ce251a971f1c)

**Comment by elynema** [comment]
@Dananji Chrome and Safari on desktop is working fine for me now for both issues reported above, but the video player is still overflowing the page horizontally in Safari on iPhone in Browserstack.

![screenshot-iPhone 15-17 0 (8)](https://github.com/user-attachments/assets/e9a64d5d-7ce2-43bb-a311-556ab4f5e0ab)

**Comment by Dananji** [comment]
@elynema Latest changes from the Ramp build were not deployed properly in `avalon-dev`, so it was still on the older CSS. Chris re-compiled them, and now latest CSS changes are in place in `avalon-dev`.

**Comment by elynema** [comment]
This is looking good on iPhone, but Android is still overflowing. I see you have #696 that isn't merged yet - is that a resolution to this issue?

![screenshot-Samsung Galaxy S24-14 0 (4)](https://github.com/user-attachments/assets/866dda07-0e1d-4346-a169-42370975aadf)

**Comment by elynema** [comment]
Tested and working fine on Chrome and Safari on desktop

@Dananji Two issues:

1. Still having overflow on Android just like before. I'm guessing #696 did not get included in the new Ramp build in Avalon-dev.
2. Tested zoom on iPhone (iOS 18) using the browser Zoom setting to 200%. The video player is way too wide for the screen in this context. See screenshot:

![screenshot-iPhone 14-18 0 (1)](https://github.com/user-attachments/assets/7dde4792-e922-4aff-b537-7efa97071983)

**Comment by Dananji** [comment]
The change for Android is included in the latest build of Ramp in Avalon, but the assets didn't compile and deploy in `avalon-dev` properly. I mentioned it to Chris and he will look into it: https://samvera.slack.com/archives/G2E762545/p1730839476879059?thread_ts=1730835289.531579&cid=G2E762545. Once this is resolved this can be tested again in Android.

I will look into the zoom issue in iPhone.

**Comment by Dananji** [comment]
We set a minimum width to the player in iOS and Android devices to `380px`, which Ramp sticks with on zoom. This is to keep all player control icons on-screen when zooming in. 

I can reduce this width to a lower value (~320px). Reducing it all the way to fit device width will result in the same issue we've seen before, where some of the player controls gets hidden.

@elynema What do you think about reducing the minimum width of the player just enough to contain all the player controls? This value is around `320px`. Or if there's anything else we can try, please let me know.

**Comment by elynema** [comment]
@Dananji I thought moving the progress bar up above was to allow us to zoom up to 200%?

**Comment by Dananji** [comment]
> I thought moving the progress bar up above was to allow us to zoom up to 200%?

No, it doesn't allow us to keep the player width fit to device width on 200% zoom. Moving the progress-bar above the controls helps us to interact with it on 200% zoom easily, because it doesn't get squished among the other controls.

In order to find a solution to this I tested the following sites on 200% zoom on iPhone;
1. VideoJS site: in the first instance it reduces the player width to fit the device width, in the second instance keeps a fix width while the player goes out of page boundaries.
<img width="403" alt="Screenshot 2024-11-05 at 4 58 34 PM" src="https://github.com/user-attachments/assets/b6e8d993-e3d7-41bb-b0bc-ffb39e2c3157">
<img width="403" alt="Screenshot 2024-11-05 at 5 04 28 PM" src="https://github.com/user-attachments/assets/19da68bb-bb3d-4a53-90d2-4e8f4903282c">

2. LinkedInLearning: zooms in the player and its controls keeping the player's width fit to device width, while some controls disappear.
<img width="403" alt="Screenshot 2024-11-05 at 5 00 00 PM" src="https://github.com/user-attachments/assets/d9f6c8d4-4413-4bc2-8aa2-4971e7062887">


> If we set a min width, then users might not be able to actually see the full content that's playing if they are zoomed, right?

Yes, this is an issue with zooming in to 200% on portrait mode with this solution.

One potential solution for this could be to aggregate the controls into a single setting menu on mobile devices in the future?

**Comment by joncameron** [comment]
No ability to identify zoom level in the browser within JS is also a difficulty with some of these methods.

**Comment by elynema** [comment]
Width is looking ok on Android, now.

Stick with our current solution for 200% Zoom, which was developed as #596. Jon will create a new issue to investigate if we can develop a solution more like Vimeo, where controls are migrated into a joint panel behind a single config button when zoom goes up.
